services:
  app:
    image: bloglist-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # to ensure node_modules not overwritten
    ports:
      - 5173:5173
    container_name: bloglist-front-dev